/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.Transformation4.calledFromGUI;
import static GUI.Transformation4.toDecimal;
import static GUI.Transformation4.toDecimalS;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Zeeshan Khan
 */

public class NewJFrame extends javax.swing.JFrame {
    
    double lat_input=5,long_input=5,height_input=5;
    Transformation4 tf=new Transformation4();
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormatSelector = new javax.swing.ButtonGroup();
        Input_Datum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LatitudeInput = new javax.swing.JTextField();
        LongitudeInput = new javax.swing.JTextField();
        HeightInput = new javax.swing.JTextField();
        Output_Datum = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LatitudeOutput = new javax.swing.JTextField();
        LongitudeOutput = new javax.swing.JTextField();
        HeightOutput = new javax.swing.JTextField();
        ConvertButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        DD = new javax.swing.JRadioButton();
        DMM = new javax.swing.JRadioButton();
        DMSS = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geodetic Transformation");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Input_Datum.setMaximumRowCount(15);
        Input_Datum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WGS84", "Everest IND-I -  Indian  Everest (India 1956) : India And Nepal", "Everest IND-B - Indian  Everest (India 1830) : Bangladesh", "NAD27  NAS-A - North American 1927 (Clarke 1866) : Eastern United States", "NAD27 NAS-B  - North American 1927 (Clarke 1866) : Western United States", "NAD27 NAS-C  - North American 1927 (Clarke 1866) :Mean Value(Conus)", "NAD27 NAS-D - North American 1927  (Clarke 1866) :Alaska", "NAD27 NAS-E - North American 1927  (Clarke 1866) :Canada", "NAD27 NAS-F - North American 1927  (Clarke 1866) :Alberta and British Columbia", "NAD27 NAS-G - North American 1927  (Clarke 1866) :East Canada", "NAD27 NAS-N - North American 1927  (Clarke 1866) :Central America", "NAD27 NAS-P - North American 1927  (Clarke 1866) :Caribbean", "NAD27 NAS-T - North American 1927  (Clarke 1866) :Cuba", "NAD27 NAS-L - North American 1927  (Clarke 1866) :Mexico", "NAD83 NAR-A -North American 1983 (GRS 80) :Alaska", "NAD83 NAR-B -North American 1983 (GRS 80) :Canada", "NAD83 NAR-C -North American 1983 (GRS 80) :Conus", "NAD83 NAR-D -North American 1983 (GRS 80) :Mexico And Central America", "NAD83 NAR-E -North American 1983 (GRS 80) :Aleutian Island", "NAD83 NAR-H -North American 1983 (GRS 80) :Hawaii", "AGD66 ZEE-K - Australian Geodetic Datum 1966 :Australia" }));
        Input_Datum.setBorder(null);
        Input_Datum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_DatumActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Datum");

        jLabel2.setText("Latitude");

        jLabel3.setText("Longitude");

        jLabel4.setText("Height");

        LatitudeInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LatitudeInputMouseExited(evt);
            }
        });
        LatitudeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatitudeInputActionPerformed(evt);
            }
        });

        LongitudeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeInputActionPerformed(evt);
            }
        });

        HeightInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightInputActionPerformed(evt);
            }
        });

        Output_Datum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WGS84", "Everest IND-I -  Indian  Everest (India 1956) : India And Nepal", "Everest IND-B - Indian  Everest (India 1830) : Bangladesh", "NAD27  NAS-A - North American 1927 (Clarke 1866) : Eastern United States", "NAD27 NAS-B  - North American 1927 (Clarke 1866) : Western United States", "NAD27 NAS-C  - North American 1927 (Clarke 1866) :Mean Value(Conus)", "NAD27 NAS-D - North American 1927  (Clarke 1866) :Alaska", "NAD27 NAS-E - North American 1927  (Clarke 1866) :Canada", "NAD27 NAS-F - North American 1927  (Clarke 1866) :Alberta and British Columbia", "NAD27 NAS-G - North American 1927  (Clarke 1866) :East Canada", "NAD27 NAS-N - North American 1927  (Clarke 1866) :Central America", "NAD27 NAS-P - North American 1927  (Clarke 1866) :Caribbean", "NAD27 NAS-T - North American 1927  (Clarke 1866) :Cuba", "NAD27 NAS-L - North American 1927  (Clarke 1866) :Mexico", "NAD83 NAR-A -North American 1983 (GRS 80) :Alaska", "NAD83 NAR-B -North American 1983 (GRS 80) :Canada", "NAD83 NAR-C -North American 1983 (GRS 80) :Conus", "NAD83 NAR-D -North American 1983 (GRS 80) :Mexico And Central America", "NAD83 NAR-E -North American 1983 (GRS 80) :Aleutian Island", "NAD83 NAR-H -North American 1983 (GRS 80) :Hawaii", "AGD66 ZEE-K - Australian Geodetic Datum 1966 :Australia" }));
        Output_Datum.setPreferredSize(new java.awt.Dimension(384, 20));

        jLabel7.setText("Output Datum");

        jLabel5.setText("Latitude");

        jLabel6.setText("Longitude");

        jLabel8.setText("Height");

        LatitudeOutput.setEditable(false);
        LatitudeOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatitudeOutputActionPerformed(evt);
            }
        });

        LongitudeOutput.setEditable(false);

        HeightOutput.setEditable(false);
        HeightOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightOutputActionPerformed(evt);
            }
        });

        ConvertButton.setText("Convert");
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Input Datum Format");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        FormatSelector.add(DD);
        DD.setSelected(true);
        DD.setText("  DD.DDDD");
        DD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDActionPerformed(evt);
            }
        });

        FormatSelector.add(DMM);
        DMM.setText("  DD MM.MMMM");
        DMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMMActionPerformed(evt);
            }
        });

        FormatSelector.add(DMSS);
        DMSS.setText("  DD MM SS.SSSS");
        DMSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMSSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DD)
                            .addComponent(DMM)
                            .addComponent(DMSS))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DD)
                .addGap(18, 18, 18)
                .addComponent(DMM)
                .addGap(18, 18, 18)
                .addComponent(DMSS)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LatitudeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(LongitudeInput)
                            .addComponent(HeightInput)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ConvertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LongitudeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LatitudeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HeightOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Output_Datum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Input_Datum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input_Datum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LatitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LongitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HeightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Output_Datum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LatitudeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LongitudeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeightOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertButton)
                    .addComponent(ResetButton))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_DatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_DatumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Input_DatumActionPerformed

    private void LatitudeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatitudeInputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LatitudeInputActionPerformed

    private void LatitudeOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatitudeOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeOutputActionPerformed

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed
        // TODO add your handling code here:
        //VERY IMPORTANT CODE
        
        double datumOut[]=new double[3];
        
        if("".equals(LatitudeInput.getText()) || "".equals(LongitudeInput.getText()) || "".equals(HeightInput.getText()))
        {
            JOptionPane.showMessageDialog(null,"Enter All Details","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            height_input=Double.parseDouble(HeightInput.getText());
            if(DD.isSelected()){
                lat_input=Double.parseDouble(LatitudeInput.getText());
                long_input=Double.parseDouble(LongitudeInput.getText());
            }else if(DMM.isSelected()){
                lat_input=toDecimal(LatitudeInput.getText());
                long_input=toDecimal(LongitudeInput.getText());
            }else if(DMSS.isSelected()){
                lat_input=toDecimalS(LatitudeInput.getText());
                long_input=toDecimalS(LongitudeInput.getText());
            }
            
            String Input=((String) (Input_Datum.getSelectedItem()));  //From ComboBox1
            Input=Input+" ";
            String Output=((String) (Output_Datum.getSelectedItem()));  //From ComboBox2
            Output=Output+" ";
        
            
            try {
                //System.out.print(Input);
                //calledFromGUI
                datumOut=calledFromGUI(lat_input,long_input,height_input,Input,Output);
                } 
            catch (IOException ex) 
            {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            HeightOutput.setText(Double.toString(datumOut[2]));
            if(DD.isSelected()){
                LatitudeOutput.setText(Double.toString(datumOut[0]));
                LongitudeOutput.setText(Double.toString(datumOut[1]));
            }else if(DMM.isSelected()){
                LatitudeOutput.setText(Integer.toString((int) datumOut[0])+" "+(datumOut[0]-(int) datumOut[0])*60);
                LongitudeOutput.setText(Integer.toString((int) datumOut[1])+" "+(datumOut[1]-(int) datumOut[1])*60);
            }else if(DMSS.isSelected()){
                double second1=(((datumOut[0]-(int) datumOut[0])*60)-(int)((datumOut[0]-(int) datumOut[0])*60))*60;
                double second2=(((datumOut[1]-(int) datumOut[1])*60)-(int)((datumOut[1]-(int) datumOut[1])*60))*60;
                LatitudeOutput.setText(Integer.toString((int) datumOut[0])+" "+(int)((datumOut[0]-(int) datumOut[0])*60)+" "+second1);
                LongitudeOutput.setText(Integer.toString((int) datumOut[1])+" "+(int)((datumOut[1]-(int) datumOut[1])*60)+" "+second2);
            }            
            
        }
    }//GEN-LAST:event_ConvertButtonActionPerformed
    //Void Convert Action Performed Closes Here
    /*Impotrtant Code Ends Here*/
    
    
    private void LatitudeInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatitudeInputMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeInputMouseExited

    private void HeightInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightInputActionPerformed

    private void HeightOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightOutputActionPerformed

    private void LongitudeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeInputActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        LatitudeOutput.setText(null);
        LongitudeOutput.setText(null);
        HeightOutput.setText(null);
        LatitudeInput.setText(null);
        LongitudeInput.setText(null);
        HeightInput.setText(null);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void DMSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DMSSActionPerformed

    private void DMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DMMActionPerformed

    private void DDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DDActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //To Run Threads (****Main Function****)
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    //END OF MAIN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertButton;
    private javax.swing.JRadioButton DD;
    private javax.swing.JRadioButton DMM;
    private javax.swing.JRadioButton DMSS;
    private javax.swing.ButtonGroup FormatSelector;
    private javax.swing.JTextField HeightInput;
    private javax.swing.JTextField HeightOutput;
    private javax.swing.JComboBox<String> Input_Datum;
    private javax.swing.JTextField LatitudeInput;
    private javax.swing.JTextField LatitudeOutput;
    private javax.swing.JTextField LongitudeInput;
    private javax.swing.JTextField LongitudeOutput;
    private javax.swing.JComboBox<String> Output_Datum;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
